source: ./src
destination: ./public

include:
  - _headers

host: 0.0.0.0

title: Code.mil
description: An experiment in open source within the Department of Defense.
email: code@dds.mil

defaults:
  - scope:
      path: ""
    values:
      layout: page
      sidenav: sidebar
      sticky_sidenav: true
  - scope:
      path: "assets"
    values:
      layout: null
  - scope:
      path: "code.json"
    values:
      layout: null

theme: uswds-jekyll

scripts:
  - /assets/uswds/js/uswds.min.js
  - /assets/js/main.js

styles:
  - /assets/css/main.css
  - /assets/css/custom.css
